export const config = [
    { name: 'Player', 
        shapeRadius: 32, 
        collisionRadius: 32, 
        speed: 5,
        fillR: 5,
        fillG: 5,
        fillB: 5, 
        outR: 255,
        outG: 0,
        outB: 0, 
        outThick: 4,
        vertices: 8 
    },
    { name: 'Enemy', 
        shapeRadius: 32,
        collisionRadius: 32, 
        minSpeed: 3,
        maxSpeed: 3, 
        outR: 255,
        outG: 255,
        outB: 255, 
        outThick: 2,
        minVert: 3,
        maxVert: 8, 
        smallLifeSpawn: 90,
        spawnInterval: 60 
    },
    { name: 'Bullet', 
        shapeRadius: 10,
        collisionRadius: 10, 
        speed: 20, 
        fillR: 255,
        fillG: 255,
        fillB: 255, 
        outR: 255,
        outG: 255,
        outB: 255,
        outThick: 2,
        vertices: 20,
        lifeSpawn: 90 
    },
]